server:
  servlet:
     context-path: /api/${gossip.api.version}
  port: 8080

gossip:
  api:
    version: v1

network:
  services:
    -
      name: 1
      host: gossip-server-1
      port: 8081
      version: v1
    -
      name: 2
      host: gossip-server-2
      port: 8082
      version: v1
    -
      name: 3
      host: gossip-server-3
      port: 8083
      version: v1
    -
      name: 4
      host: gossip-server-4
      port: 8084
      version: v1
    -
      name: 5
      host: gossip-server-5
      port: 8085
      version: v1

spring:
  application.name: gossip-client
  hateoas:
    use-hal-as-default-json-media-type: false


