server:
  servlet:
     context-path: /api/${gossip.api.version}

gossip:
  id: 1
  api:
    version: v1
  timeout: 2

network:
  services:
    -
      name: 1
      host: gossip-server-1
      port: 8081
      version: v1
    -
      name: 2
      host: gossip-server-2
      port: 8082
      version: v1
    -
      name: 3
      host: gossip-server-3
      port: 8083
      version: v1

spring:
  application.name: gossip-server
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    com.network.http.rest_template:  ERROR

---
spring:
  profiles: debug

logging:
  level:
     com.gossip.server:  DEBUG


---
spring:
  profiles: one

network:
  services:
    -
      name: 2
      host: gossip-server-2
      port: 8082
      version: v1
    -
      name: 3
      host: gossip-server-3
      port: 8083
      version: v1

---
spring:
  profiles: two

network:
  services:
    -
      name: 1
      host: gossip-server-1
      port: 8081
      version: v1
    -
      name: 3
      host: gossip-server-3
      port: 8083
      version: v1

---
spring:
  profiles: three

network:
  services:
    -
      name: 1
      host: gossip-server-1
      port: 8081
      version: v1
    -
      name: 2
      host: gossip-server-2
      port: 8082
      version: v1
